### ISSUE TITLE
need some help ( any example ) 

### ISSUE THREAD

**Issue by amin0u** [xseignard/cordovarduino#38] opened 2015-09-17 17:29 UTC
hello i want some help !

i like to build an app to controle 4 led by 4 button

using cordovarduino  ( arduino uno r3 )

i search example or tutorial  .. but  no result 

con someone give me an example  ( simple code )

**Comment by amin0u** [comment] 2015-10-02 21:19
no found device probleme !
vid : 2341
pid : 0043
of my arduino 

i don't know what is the probleme !

<!DOCTYPE html>
<html>
<head>
    <title> Example</title>

    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" charset="utf-8">

    //
    document.addEventListener("deviceready", onDeviceReady, false);

    // device APIs are available
    //
    function onDeviceReady() {
       var errorCallback = function(message) {
    alert('Error: ' + message);
};

serial.requestPermission({vid : '2341' ,pid : '0043'},
    function(successMessage) {
        serial.open(
            {baudRate: 9600},
            function(successMessage) {
                serial.write(
                    '1',
                    function(successMessage) {
                        alert(successMessage);
                    },
                    errorCallback
                );
            },
            errorCallback
        );
    },
    errorCallback
); 
    }


 
    </script>
</head>
<body>

</body>
</html>

**Comment by xseignard** [comment] 2015-11-01 10:18
Hello @amin0u you know how to use cordova, right?

If so, use this as your `index.js`
```javascript
var app = {
	initialize: function() {
		document.addEventListener('deviceready', this.onDeviceReady, false);
	},
	onDeviceReady: function() {
		var potText = document.getElementById('pot');
		var delta = document.getElementById('delta');
		var on = document.getElementById('on');
		var off = document.getElementById('off');
		var open = false;
		var str = '';
		var lastRead = new Date();
		
		var errorCallback = function(message) {
			alert('Error: ' + message);
		};
		// request permission first
		serial.requestPermission(
			// if user grants permission
			function(successMessage) {
				// open serial port
				serial.open(
					{baudRate: 9600},
					// if port is succesfuly opened
					function(successMessage) {
						open = true;
						// register the read callback
						serial.registerReadCallback(
							function success(data){
								// decode the received message
								var view = new Uint8Array(data);
								if(view.length >= 1) {
									for(var i=0; i < view.length; i++) {
										// if we received a \n, the message is complete, display it
										if(view[i] == 13) {
											// check if the read rate correspond to the arduino serial print rate
											var now = new Date();
											delta.innerText = now - lastRead;
											lastRead = now;
											// display the message
											var value = parseInt(str);
											pot.innerText = value;
											str = '';
										}
										// if not, concatenate with the begening of the message
										else {
											var temp_str = String.fromCharCode(view[i]);
											var str_esc = escape(temp_str);
											str += unescape(str_esc);
										}
									}
								}
							},
							// error attaching the callback
							errorCallback
						);
					},
					// error opening the port
					errorCallback
				);
			},
			// user does not grant permission
			errorCallback
		);

		on.onclick = function() {
			console.log('click');
			if (open) serial.write('1');
		};
		off.onclick = function() {
			if (open) serial.write('0');
		}
	}
};

app.initialize();
```

then this as your `index.html`
```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Potentiometer value</h1>
            <p>Value <span id="pot">...</span></p>
            <p id="delta">...</p>
            <button id="on">On</button>
            <button id="off">Off</button>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>
```

and this as your arduino code, with a potentiometer on A0 and a led on 13
```arduino
#define POT A0
#define LED 13

unsigned long previousMillis;
int interval = 50;

void setup() {
	Serial.begin(9600);
	pinMode(POT, INPUT);
	pinMode(LED, OUTPUT);
}

void loop() {
	if (Serial.available() > 0) {
		char i = Serial.read();
		switch (i) {
			case '0':
				digitalWrite(LED, LOW);
				break;
			case '1':
				digitalWrite(LED, HIGH);
				break;
		}
	}
	if (millis() - previousMillis >= interval) {
		previousMillis = millis();
		int value = analogRead(POT);
		Serial.println(value);
	}
}
```

**Comment by xseignard** [comment] 2015-11-17 16:57
I'm closing it,
Feel free to reopen it if you're still stuck.

BTW some updates from your side would be appreciated...

**Closed by xseignard** 2015-11-17 16:57 UTC

**Comment by akankshadixit** [comment] 2016-04-28 00:05
hey xseignard
what's the use of this piece of code in index.js
  var now = new Date(); 
   delta.innerText = now - lastRead;
   lastRead = now;

Is it for arduino to properly communicate with our app??
Also, why are we using the millis in arduino??

**Comment by xseignard** [comment] 2016-04-28 00:32
Hello, the pièce of code in index.js you showed is here to check how is the latency between arduino and the app. 

Since we are using millis in arduino code to send a read every 50ms, we check if the time delta is also 50ms in the index.js side.

You can remove this code if don't needed. It's here only for demo purposes

**Comment by xseignard** [comment] 2016-04-28 00:35
And please read this to see why I use `millis()` : https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay

**Comment by akankshadixit** [comment] 2016-04-28 07:04
I am working with an app to register reads. This is my index.js


var open =false;
var value='';
var str='';

var app = {
	initialize: function() {
		document.addEventListener('deviceready', this.onDeviceReady, false);
	},
     	onDeviceReady: function() {	

		console.log("alert");
		
		var errorCallback = function(message) {
			alert('Error: ' + message);
		};
		// request permission first
		serial.requestPermission(
			// if user grants permission
			function(successMessage) {
				// open serial port
				serial.open(
					{baudRate: 9600, sleepOnPause: false},
					// if port is succesfuly opened
					function(successMessage) {
						open = true;
						// register the read callback
						serial.registerReadCallback(
							function success(data){

								// decode the received message
								var view = new Uint8Array(data);
								if(view.length >= 1) 
								{
									for(var i=0; i < view.length; i++) 
									{
										// if we received a \n, the message is complete, display it
										if(view[i] == 13) {
											// check if the read rate correspond to the arduino serial print rate
										
											
											// display the message
                                            value = str;
											
											str = '';
										}
										// if not, concatenate with the begening of the message
										else {
											var temp_str = String.fromCharCode(view[i]);
											var str_esc = escape(temp_str);
											str += unescape(str_esc);
										}
									}
									alert(value);
									if(value =='play')
									{										
										document.getElementById("myNav").style.height = "0%";
										value='';
									}
								}
								

							},
							// error attaching the callback
							errorCallback
						);
					},
					// error opening the port
					errorCallback
				);
			},
			// user does not grant permission
			errorCallback


		);

      

	}
};


app.initialize();

**Comment by akankshadixit** [comment] 2016-04-28 07:11
I want help with an app that I am trying to make using cordovarduino. I want to basically remove a screen whenever the analog read is above a value of 650. I am sending a play string whenever the value is above 650. On receiving a play the screen size should be reduced to 0%.
The problem is the play string is received first time but after that it does not work.
I am attaching my index.js and arduino code

`
var open =false;
var value='';
var str='';

var app = {
	initialize: function() {
		document.addEventListener('deviceready', this.onDeviceReady, false);
	},
     	onDeviceReady: function() {	

		console.log("alert");
		
		var errorCallback = function(message) {
			alert('Error: ' + message);
		};
		// request permission first
		serial.requestPermission(
			// if user grants permission
			function(successMessage) {
				// open serial port
				serial.open(
					{baudRate: 9600, sleepOnPause: false},
					// if port is succesfuly opened
					function(successMessage) {
						open = true;
						// register the read callback
						serial.registerReadCallback(
							function success(data){

								// decode the received message
								var view = new Uint8Array(data);
								if(view.length >= 1) 
								{
									for(var i=0; i < view.length; i++) 
									{
										// if we received a \n, the message is complete, display it
										if(view[i] == 13) {
											// check if the read rate correspond to the arduino serial print rate
										
											
											// display the message
                                            value = str;
											
											str = '';
										}
										// if not, concatenate with the begening of the message
										else {
											var temp_str = String.fromCharCode(view[i]);
											var str_esc = escape(temp_str);
											str += unescape(str_esc);
										}
									}
									alert(value);
									if(value =='play')
									{										
										document.getElementById("myNav").style.height = "0%";
										value='';
									}
								}
								

							},
							// error attaching the callback
							errorCallback
						);
					},
					// error opening the port
					errorCallback
				);
			},
			// user does not grant permission
			errorCallback


		);

      

	}
};


app.initialize();`

**Comment by akankshadixit** [comment] 2016-04-28 07:12
then this is the arduino code
`#include "PinChangeInterrupt.h"
#define POT A0
#define LED 13

unsigned long previousMillis;
int interval = 150;
int count =0;
void setup() {
	
	pinMode(POT, INPUT);
	pinMode(LED, OUTPUT);
  pinMode(2,OUTPUT);
  pinMode(3,INPUT_PULLUP);
  attachPinChangeInterrupt(digitalPinToPinChangeInterrupt(3), tick, RISING);
 
  Serial.begin(9600);
   digitalWrite(2,LOW);
}

void loop() {
/*	if (Serial.available() > 0) {
		char i = Serial.read();
		switch (i) {
			case '0':
				digitalWrite(LED, LOW);
				break;
			case '1':
				digitalWrite(LED, HIGH);
				break;
		}
	} */
	if (millis() - previousMillis >= interval) {
		previousMillis = millis();
		int value = analogRead(POT);
    if(value>650){
     digitalWrite(2,HIGH); 
		Serial.println("play");
		}
	}
  if(count>=10){
    count=0;
    digitalWrite(2,LOW);
  }
 
}

void tick(void){
  count++;
  }`

**Comment by akankshadixit** [comment] 2016-04-28 07:13
Can you please help me with this. Thanks in advance!!!

**Comment by xseignard** [comment] 2016-04-28 09:03
Please create a separate issue and use proper markdown styling, you code is impossible to read outside the code tags

regards

**Comment by sdesalas** [comment] 2016-04-28 11:50
Hiya, very useful example thanks Xavier! I used it in the [spaceapps hackathon](https://github.com/sdesalas/spaceapps2016-TEAM) recently. Maybe a food idea to copy to readme or wiki?

Cherio, Steven

**Comment by xseignard** [comment] 2016-04-28 12:42
Hello @sdesalas 
Nice app and congrats for the win!

That's sure the README needs some love, if you want to send a PR it is more than welcome since I'm struggling to find time to do it.

This issue was the starting point of a clean and full example on how this lib works, you can find it here: https://github.com/xseignard/demoCordovarduino

Regards

Xavier
